apiVersion: v1
kind: Pod
metadata:
  name: my-web
  labels: 
    env : production
    app : main
    tier: frontend


spec:
  containers:
    - name: container-nginx
      image: nginx:latest
      ports:
        - containerPort: 80
  